### ISSUE TITLE
[BUG] error when trying to migrate v1 to v2 vault using the flashloan tool

### ISSUE THREAD

**Issue by maartenvandoorn** [alchemix-finance/alchemix-v2-frontend#352]
### What happened?

Hi guys, I've finally gotten around to migrating to Alchemix v2. However, I'm encountering an error when trying to migrate my altETH position. I get two different error logs, sometimes the first and sometimes the second. I've copied them below. What should I do to fix this?

Timestamp:

1659957916992
(8/8/2022)

Error Message:

transaction failed (transactionHash="0x28335c2329013179f3216d397ab2396f41568c1176a85cbde6555d0948c40fd2", transaction={"hash":"0x28335c2329013179f3216d397ab2396f41568c1176a85cbde6555d0948c40fd2","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x2642E2883BC7344a42334624AC7c9d9254E03D37","gasPrice":{"type":"BigNumber","hex":"0x0197b013c4"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x0197b013c4"},"gasLimit":{"type":"BigNumber","hex":"0x2dc6c0"},"to":"0x0256fC7bA8d1513Be9661c504F36e075942d9A49","value":{"type":"BigNumber","hex":"0x00"},"nonce":54,"data":"0xe5fdddf9000000000000000000000000c4c319e2d4d66cca4464c0c2b32c9bd23ebe784e00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062bf725dc4cdf947aa79ca2aaccd4f385b13b5c000000000000000000000000a258c4606ca8206d8aa700ce2143d7db854d168c0000000000000000000000000000000000000000000000001ccecea7d218d8a1000000000000000000000000000000000000000000000000382cdfc74016d9940000000000000000000000000000000000000000000000001ba420a76c883947","r":"0x7349d61776ef6d0c26b72c11fdd9b5c30ac97827c93ade2c9a5bbacb69714231","s":"0x44d01abff3f45ee6fff84b6be22440bb65ea852cc5d15eb05d301d332348f56e","v":1,"creates":null,"chainId":0}, receipt={"to":"0x0256fC7bA8d1513Be9661c504F36e075942d9A49","from":"0x2642E2883BC7344a42334624AC7c9d9254E03D37","contractAddress":null,"transactionIndex":247,"gasUsed":{"type":"BigNumber","hex":"0x0ab2a0"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x72944aa2ac5ee68eede5874dab53208253e6475a39cc9504fd03127e5e4d904e","transactionHash":"0x28335c2329013179f3216d397ab2396f41568c1176a85cbde6555d0948c40fd2","logs":[],"blockNumber":15301275,"confirmations":3,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x01135aee"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x014bfe4f2f"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.5.0)
Timestamp:

1659957948047
(8/8/2022)

Error Message:

cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32000,"message":"execution reverted"}, method="estimateGas", transaction={"from":"0x2642E2883BC7344a42334624AC7c9d9254E03D37","to":"0xf8317BD5F48B6fE608a52B48C856D3367540B73B","data":"0x415f12400000000000000000000000000000000000000000000000000000000000000001","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)

---

Error Message:

cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32000,"message":"execution reverted"}, method="estimateGas", transaction={"from":"0x2642E2883BC7344a42334624AC7c9d9254E03D37","to":"0xf8317BD5F48B6fE608a52B48C856D3367540B73B","data":"0x415f12400000000000000000000000000000000000000000000000000000000000000001","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)

---
When I try to migrate again, a pop up shows up that stops the interaction from happening:

Something went wrong

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32000,"message":"execution reverted"}, method="estimateGas", transaction={"from":"0x2642E2883BC7344a42334624AC7c9d9254E03D37","to":"0xf8317BD5F48B6fE608a52B48C856D3367540B73B","data":"0x415f12400000000000000000000000000000000000000000000000000000000000000001","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)

--

URL of the original failed transaction: https://etherscan.io/tx/0x28335c2329013179f3216d397ab2396f41568c1176a85cbde6555d0948c40fd2

### Steps to reproduce

1. Initiate "migrate legacy alETH position" (using Chrome and Metamask)
2. Transaction starts but fails: https://etherscan.io/tx/0x28335c2329013179f3216d397ab2396f41568c1176a85cbde6555d0948c40fd2
3. Try to initiate "migrate legacy alETH position" again
4. Transaction won't even start. Instead a pop-up appears. See above for details
...

### What browser were you using?

Chrome

**Comment by n4n0GH** [comment]
Seeing how a new version migrator is just waiting for the [AIP to be voted on and passed](https://forum.alchemix.fi/public/d/348-aip-61-migrate-v1-to-v2-and-sunset-v1), I'm closing this.
