### ISSUE TITLE
[BUG] Lost funds?

### ISSUE THREAD

**Issue by LeifOnEarth** [alchemix-finance/alchemix-v2-frontend#370]
### Contact Details

leifinthetrees@protonmail.com

### What happened?

Funds eaten by smart contract!?

Hi gang, while attempting to withdraw my loan of alETH to Optimism it appears it was sent to one of your smart contracts internally rather than my wallet address. I'm currently out half an ETH and could really use some help in 1) in getting it back and 2) making sure this doesn't happen to others in future.

### Steps to reproduce

1. Wasn't fully clear on purpose of Transmuter initially. After taking out my loan I was attempting to figure out how to remove it back to my Brave wallet. Thought I could change it to WETH in the transmuter if I went through the steps. It was after Vaults... seemed like it made sense as the next step of the process.
2. Deposited my just-loaned alETH into the Van Helmont Transmuter - 0.499 alETH now visible in the 2nd "withdraw" column 
3. Tried to use the withdraw button to take it out - it failed. Hours later after work I went back to figure it out.
4. Realized my mistake and converted it back to alETH - 0.499 alETH now visible in the first "deposit" column again
5. Went to Swap in order to bridge it elsewhere. 0.499alETH was visible on Ethereum Mainnet. Clicked Max and selected bridging to Optimism.
6. Transaction failed once with an error message about gas. Checked gas, saw I had enough, figured the network was just busy.
7. Tried again, same error message. Checked which network I was on, reloaded the page, tried a third time. Transaction confirmed & successful.
8. Added alETH to my Brave wallet as it wasn't previously linked. Waited for it to show up. Realized it was weird it didn't ask me about adding the alETH token... and nothing shows up. 
9. Checked Etherscan and found the transaction that I thought was bridging my funds from from the Ethereum Network to Optimistic Ethereum (0x159d783591d2e746a3CC29A2956c738C68f51979) actually was actually somehow talking to another Alchemix smart contract (0x362fA9D0bCa5D19f743Db50738345ce2b40eC99f) - this happened at Txn Hash 0x2e1cb72cc784b9cc00210edf49f8b5bbcb957faf6a43bf9312f632eec9a8f563.
10. Digging deeper into this hash, it appears it sent my 0.492 ETH to a null address????????
11. Is this a burn address? Dear god please let it not be a burn address. PLEASE HELP :'(
...

### What browser were you using?

Brave

**Comment by n4n0GH** [comment]
As [explained on the forum](https://forum.alchemix.fi/public/d/346-smart-contract-ate-my-aleth/3) a last step is needed to complete the process:

> One step sends your mainnet alETH to the bridge, which in return mints you the bridge asset on the target network. If you check out your wallet on optimism you'll see you own 0.492 "Multichain alETH". If you go to our bridge page again once connected to Optimism, there should be a message reminding you to swap the bridge token to the network's canonical token. Do that please and you'll end up with a usable token on Optimism.
