### ISSUE TITLE
[BUG] : Slowloris Dos 

### ISSUE THREAD

**Issue by nishant8990** [alchemix-finance/alchemix-v2-frontend#383]
### Contact Details

royniss8990@gmail.com

### What happened?

Bug Name :- Slowloris Dos Attack

Bug Target : https://alchemix.fi/

Bug Description :-

Slowloris is a denial-of-service attack program which allows an
attacker to overwhelm a targeted server by opening and maintaining
many simultaneous HTTP connections between the attacker and the target

How does it work :-

  Slowloris is an application layer attack which operates by utilizing
partial HTTP requests. The attack functions by opening connections to
a targeted Web server and
then keeping those connections open as long as it can.

Slowloris is not a category of attack but is instead a specific attack
tool designed to allow a single machine to take down a server without
using a lot of bandwidth.
Unlike bandwidth-consuming reflection-based DDoS attacks such as NTP
amplification, this type of attack uses a low amount of bandwidth, and
instead aims to use up server resources
with requests that seem slower than normal but otherwise mimic regular
traffic. It falls in the category of attacks known as “low and slow”
attacks.
The targeted server will only have so many threads available to handle
concurrent connections. Each server thread will attempt to stay alive
while waiting for the slow request to complete,
 which never occurs.
When the server’s maximum possible connection has been exceeded, each
additional connection will not be answered and denial-of-service will
occur.

How to mitigate :-

For web servers that are vulnerable to Slowloris, there are ways to
mitigate some of the impact. Mitigation options for vulnerable servers
can be broken down into 3 general categories:

1) Increase server availability - Increasing the maximum number of
clients the server will allow at any one time will increase the number
of connections the attacker must make before they can overload the
server. Realistically, an attacker may scale the number of attacks to
overcome server capacity regardless of increases.

2) Rate limit incoming requests - Restricting access based on certain
usage factors will help mitigate a Slowloris attack. Techniques such
as limiting the maximum number of connections a single IP address is
allowed to make, restricting slow transfer speeds, and limiting the
maximum time a client is allowed to stay connected are all approaches
for limiting the effectiveness of low and slow attacks.

3) Cloud-based protection - Use a service that can function as a
reverse proxy, protecting the origin server.

### Steps to reproduce

Steps to reproduce :- ( Use kali linux OS)

1)Open terminal and enter command

   > git clone https://github.com/llaera/slowloris.pl.git

2) It will download the [slowloris.pl](http://slowloris.pl/) folder on home

3) Go to that folder and open this folder in terminal

4) then Enter command

     perl [slowloris.pl](http://slowloris.pl/) -dns <YOUR-SITE-IP-ADDRESS>

5) Wait to complete

6) It will lower your site's accessibility.

### What browser were you using?

Other

### If you selected "Other" above, fill in the browser you used here.

kali linux

**Comment by n4n0GH** [comment]
As this is also reported on our immunefi bug bounty (which is the correct place to report), I'll close this.

**Comment by nishant8990** [comment]
Give me an update on this on immunefi. Let me know..
