### ISSUE TITLE
[BUG] Issue staking yearn eth token yvWETH.

### ISSUE THREAD

**Issue by Robo-Odin** [alchemix-finance/alchemix-v2-frontend#407]
### Contact Details

Robo-Odin

### What happened?

Tried to deposit yearn eth deposit tokens. Got  "Something went wrong $e.deposit is not a function"
Pushed slippage up to 2% and it didn't work. So I left the vault and weth deposit worked fine.

### Steps to reproduce

1.Get yvWETH
2. Try and stake
3. Profit
...

### Expected behavior

I expected it to deposit. 

### What browser were you using?

Chrome

**Comment by kookoo-tzu** [comment]
Still experiencing this issue. What's the fix?

**Comment by n4n0GH** [comment]
getting to debugging this now; so what happens is that because for the aave vault we have to use gateways, the yearn vault now behaves like that as well when it shouldn't.
