### ISSUE TITLE
[BUG] Error when trying to connect wallet on Fantom network

### ISSUE THREAD

**Issue by imimim-username** [alchemix-finance/alchemix-v2-frontend#422]
### Contact Details

imimim.email@gmail.com

### What happened?

When trying to connect my wallet to Alchemix on Fantom, I get an error that says "Action required in [x]. Please switch the active account in your wallet." Where X is "Metamask" or "Brave Wallet," as I've tried it with both. Both are in Windows 10.

In Brave, my wallet settings are the following:
Chain id: 250
Name: Fantom
Currency symbol: FTM
Decimals: 18
RPC: https://rpc.ftm.tools/
Block explorer: https://ftmscan.com

In Metamask, my wallet settings are the following:
Network Name: Fantom Opera
RPC: https://rpcapi.fantom.network
Chain ID: 250
Currency symbol: FTM
Block explorer: https://ftmscan.com/

I've tried clearing site data and things like that, and the issue persists.

![image](https://user-images.githubusercontent.com/100382074/193452560-af3a6188-c7b0-4721-a0f2-abe3c8e94516.png)

### Steps to reproduce

1. Activate wallet
2. Switch to Fantom network
3. Navigate to alchemix.fi with wallet-enabled browser
4. Click "Connect Wallet"
5. Click appropriate wallet (e.g.,Metamask or Brave)
6. Observe error message

### Expected behavior

What is expected is that the site will connect to my Fanton-connected wallet, and that I'd be able to observe my positions and sign transactions.

### What browser were you using?

Other

### If you selected "Other" above, fill in the browser you used here.

Chrome for Metamask, and Brave for Brave Wallet

**Comment by akensig** [comment]
Hello, similar issue but this is on Firefox when I attempt to interact over Arbitrum. I bridged gALCX to Arbitrum via Alchemix.Fi front end, tried to bridge back, but get this same error message: Please switch the active account in your wallet.

**Comment by diorskins** [comment]
Same here. I use Chrome and I can access ETH and Optimism like normal but for Fantom and Arbitrum I can't access the dashboards at all. It say's connect wallet and show's that my wallet is connected but the site doesn't allow me access

**Comment by n4n0GH** [comment]
Most likely that the bug is caused by #419 

![Screenshot 2022-10-04 at 9 59 34 AM](https://user-images.githubusercontent.com/27410256/193766214-4c3bbca9-abcb-4e35-8cee-ac84a56afcec.png)
