### ISSUE TITLE
[BUG] {"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT",...

### ISSUE THREAD

**Issue by 0xJonHoldsCrypto** [alchemix-finance/alchemix-v2-frontend#456]
### Contact Details

jon@bloq.com zane@bloq.com

### What happened?

{"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0xD8c84eaC995150662CC052E6ac76Ec184fcF1122","to":"0xA067C885d958aec176eC3D8dAdc847e0c9384809","data":"0xf45346dc000000000000000000000000d1c117319b3595fbc39b471ab1fd485629eb05f200000000000000000000000000000000000000000000000002b49204e6a5aa38000000000000000000000000d8c84eac995150662cc052e6ac76ec184fcf1122","accessList":null},"error":{"code":-32000,"message":"execution reverted"}}

### Steps to reproduce

1. Approve any Vesper asset (ie: vaETH)
2. Actual deposit will trigger this warning
...

### Expected behavior

Expected a confirmation in injected wallet

### What browser were you using?

Brave

**Comment by 0xJonHoldsCrypto** [comment]
Appears that Vesper assets are not depositing due to a decimal issue - naked assets have no problems. vaXXX assets including vaUSDC (different decimalization than rest)

**Comment by n4n0GH** [comment]
haven't tried with vaETH but can confirm that decimals are an issue with vaUSDC; so instead of keeping the 6 decimal config from USDC, vaUSDC is the first asset we added that essentially doesn't conform to that standard. we're currently working on a fix for this.

**Comment by 0xJonHoldsCrypto** [comment]
Much appreciated!

Jon Greenwood
Governance Integrations @ Governor DAO
________________________________
