### ISSUE TITLE
[BUG] Cannot migrate DAI position to v2, UNPREDICTABLE_GAS_LIMIT error appears

### ISSUE THREAD

**Issue by elterko** [alchemix-finance/alchemix-v2-frontend#459]
### Contact Details

josemvillar@gmail.com

### What happened?

Upon trying to migrate mi DAI vault from v1 to v2 UNPREDICTABLE_GAS_LIMIT red sign pops up, no way of manually adjusting gas limit as MM window does not render.
I have already paid my debt in v1, want to withdraw in v2 as fees are sickening high, cannot migrate.

Complete message:
`cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x4XXXXXXXXXXXXXXXXXXXXXXXXXX9E46","to":"0xc21D353FF4ee73C572425697f4F5aaD2109fe35b","data":"0x2e1a7d4d0000000000000000000000000000000000000000000000000000000000000001","accessList":null}, error={"code":-32603,"message":"execution reverted","data":{"originalError":{"code":3,"data":"0xc50656df00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000019557365722068617320616c7265616479206d6967726174656400000000000000","message":"execution reverted"}}}, code=UNPREDICTABLE_GAS_LIMIT, `version=providers/5.7.1)``

Please, I need my money ASAP

Tested under Firefox 102, Ubuntu 21.10, MM 10.22.2 and Ledger Nano X

### Steps to reproduce

1.
2.
3.
...

### What browser were you using?

Firefox

**Comment by n4n0GH** [comment]
this has been resolved; essentially repaying your debt in v1 makes migrating through our system impossible. please don't do steps manually unless you absolutely know what you're doing.
