### ISSUE TITLE
[BUG] {"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT",...

### ISSUE THREAD

**Issue by TheGreatGildo** [alchemix-finance/alchemix-v2-frontend#558]
### What happened?

{"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0xf153FB08c86A5c4c10BBF31617467000E2C8eA4e","to":"0xb46eE2E4165F629b4aBCE04B7Eb4237f951AC66F","data":"0x94bf804d00000000000000000000000000000000000000000000001b1ae4d6e2ef500000000000000000000000000000f153fb08c86a5c4c10bbf31617467000e2c8ea4e","accessList":null},"error":{"code":-32603,"message":"execution reverted","data":{"originalError":{"message":"execution reverted","code":3,"data":"0xe7e40b5b000000000000000000000000cb8fa9a76b8e203d8c3797bf438d8fb81ea3326a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000482b4290000000000000000000000000000000000000000000000000000000000"}}}}

### Steps to reproduce

1. deposit usdc into the aave vault
2. try to borrow
3. txn doesnt go to wallet get this error
...
<img width="1572" alt="image" src="https://github.com/alchemix-finance/alchemix-v2-frontend/assets/46918472/e65022e1-be95-41fc-b2ac-b60e5507d0d6">

### What browser were you using?

Firefox

**Comment by n4n0GH** [comment]
Note: this is happening on Arbitrum.

**Comment by n4n0GH** [comment]
issue lies with whitelisting on the contracts
